### ISSUE TITLE
Example for empty tile parameter

### ISSUE THREAD

**Issue by dborchers87** [AMDmi3/tiletool#3]
Can someone give me an example codeline for the -e param? I dont know how to use it exactly.

**Comment by AMDmi3** [comment]
Just set it to path to a tile file you want to fill empty space with.

**Comment by dborchers87** [comment]
When i do this i will get the message: Cannot load empty title: Invalid argument

My action is:
tiletool -e --empty-tile=C:\Users\borchers\Documents\cache2\cache2\18\137459\85770.png -z 18 -i C:\Users\borchers\Documents\cache2\cache2 -o C:\Users\borchers\Documents\cache2\output -l C:\Users\borchers\Documents\cache2\mt3

**Comment by AMDmi3** [comment]
Your command line is indeed incorrect, it should be either ```-e C:\Users\borchers\Documents\cache2\cache2\18\137459\85770.png``` or ```--empty-tile=C:\Users\borchers\Documents\cache2\cache2\18\137459\85770.png```.
